# Generated by Django 6.0.1 on 2026-03-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CauHoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('loai_cau_hoi', models.CharField(choices=[('TEXT', 'Câu hỏi ngắn'), ('RADIO', 'Trắc nghiệm'), ('GRID', 'Dạng lưới'), ('SELECT', 'Menu thả xuống'), ('CHECKBOX', 'Hộp kiểm')], max_length=20)),
                ('system_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('thu_tu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('ma_gv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('chuc_vu', models.CharField(max_length=100)),
                ('hoc_vi', models.CharField(max_length=100)),
                ('chuyen_mon', models.CharField(max_length=255)),
                ('so_dien_thoai', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='HoiDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hoi_dong', models.CharField(max_length=255)),
                ('thoi_gian', models.DateTimeField()),
                ('dia_diem', models.CharField(max_length=255)),
                ('ngay_bao_ve', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_vai_tro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoiDong_GiangVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.giangvien')),
                ('hoi_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.hoidong')),
            ],
        ),
        migrations.CreateModel(
            name='KyThucTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ky', models.CharField(max_length=255)),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('gv_phu_trach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.giangvien')),
            ],
        ),
        migrations.AddField(
            model_name='hoidong',
            name='ky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap'),
        ),
        migrations.CreateModel(
            name='LuaChon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung_option', models.CharField(max_length=255)),
                ('loai_option', models.CharField(choices=[('NORMAL', 'Trắc nghiệm'), ('ROW', 'Hàng (Grid)'), ('COLUMN', 'Cột (Grid)')], default='NORMAL', max_length=10)),
                ('cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lua_chon', to='Home.cauhoi')),
            ],
        ),
        migrations.CreateModel(
            name='MauKhaoSat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_form', models.CharField(max_length=255)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
            ],
        ),
        migrations.AddField(
            model_name='cauhoi',
            name='mau_khao_sat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cau_hoi', to='Home.maukhaosat'),
        ),
        migrations.CreateModel(
            name='NhiemVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhiem_vu', models.CharField(max_length=255)),
                ('han_nop', models.DateTimeField()),
                ('mo_ta', models.TextField()),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuTraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_nop', models.DateTimeField(auto_now_add=True)),
                ('mau_khao_sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.maukhaosat')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietTraLoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_tri', models.TextField()),
                ('cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.cauhoi')),
                ('phieu_tra_loi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='Home.phieutraloi')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('ma_sv', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('lop', models.CharField(max_length=50)),
                ('ky_hien_tai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.kythuctap')),
            ],
        ),
        migrations.AddField(
            model_name='phieutraloi',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sinhvien'),
        ),
        migrations.CreateModel(
            name='PhanCongGVHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_phan_cong', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.IntegerField(default=1)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.giangvien')),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='HoiDong_SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoi_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.hoidong')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='BangDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_qua_trinh', models.FloatField(blank=True, null=True)),
                ('diem_doanh_nghiep', models.FloatField(blank=True, null=True)),
                ('diem_bao_cao', models.FloatField(blank=True, null=True)),
                ('diem_tong_ket', models.FloatField(blank=True, null=True)),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='BaiNop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='assignments/')),
                ('ten_file', models.CharField(max_length=255)),
                ('thoi_gian_nop', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(max_length=50)),
                ('nhiem_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.nhiemvu')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien_KyThucTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ky_thuc_tap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='TaiLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mo_ta', models.TextField()),
                ('ten_tai_lieu', models.CharField(max_length=255)),
                ('duong_dan_file', models.FileField(upload_to='documents/')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('gv_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.giangvien')),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
            ],
        ),
        migrations.CreateModel(
            name='TyLeDiem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_gvhd', models.FloatField(default=0.4)),
                ('diem_hoidong', models.FloatField(default=0.4)),
                ('diem_doanhnghiep', models.FloatField(default=0.2)),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.vaitro')),
            ],
        ),
    ]
