# Generated by Django 6.0.1 on 2026-03-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChucVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuc_vu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChuyenMon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_chuyen_mon', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HocVi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hoc_vi', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='chuyen_mon',
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='chuc_vu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.chucvu'),
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='hoc_vi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.hocvi'),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='chuyen_mon',
            field=models.ManyToManyField(to='Home.chuyenmon'),
        ),
    ]
