# Generated by Django 6.0.1 on 2026-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_chucvu_chuyenmon_hocvi_remove_giangvien_chuyen_mon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giangvien',
            name='chuc_vu',
            field=models.CharField(choices=[('Giảng viên', 'Giảng viên'), ('Trưởng bộ môn', 'Trưởng bộ môn'), ('Giáo vụ', 'Giáo vụ')], default='Giảng viên', max_length=100),
        ),
        migrations.RemoveField(
            model_name='giangvien',
            name='chuyen_mon',
        ),
        migrations.AlterField(
            model_name='giangvien',
            name='hoc_vi',
            field=models.CharField(choices=[('Thạc sĩ', 'Thạc sĩ'), ('Tiến sĩ', 'Tiến sĩ'), ('Phó Giáo sư', 'Phó Giáo sư'), ('Giáo sư', 'Giáo sư')], default='Thạc sĩ', max_length=100),
        ),
        migrations.DeleteModel(
            name='ChucVu',
        ),
        migrations.DeleteModel(
            name='ChuyenMon',
        ),
        migrations.AddField(
            model_name='giangvien',
            name='chuyen_mon',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HocVi',
        ),
    ]
