# Generated by Django 6.0.1 on 2026-03-09 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_giangvien_chuc_vu_remove_giangvien_chuyen_mon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vaitro',
            name='id',
        ),
        migrations.AddField(
            model_name='vaitro',
            name='role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nguoidung_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
