# Generated by Django 6.0.1 on 2026-03-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_nguoidung_id_remove_vaitro_id_vaitro_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
