# Generated by Django 6.0.1 on 2026-03-11 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_nguoidung_password_nguoidung_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhanCongGVPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_phan_cong', models.DateTimeField(auto_now_add=True)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.giangvien')),
                ('ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.kythuctap')),
            ],
            options={
                'unique_together': {('giang_vien', 'ky')},
            },
        ),
    ]
