# Generated by Django 4.2.19 on 2026-03-16 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_phanconggvpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cauhoi',
            name='system_tag',
        ),
        migrations.RemoveField(
            model_name='luachon',
            name='loai_option',
        ),
        migrations.AddField(
            model_name='maukhaosat',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maukhaosat',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maukhaosat',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bainop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bangdiem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='loai_cau_hoi',
            field=models.CharField(choices=[('TEXT', 'Câu hỏi ngắn'), ('RADIO', 'Trắc nghiệm'), ('LIKERT', 'Đánh giá 1-5'), ('SELECT', 'Menu thả xuống'), ('CHECKBOX', 'Hộp kiểm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='chitiettraloi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chitiettraloi',
            name='phieu_tra_loi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Home.phieutraloi'),
        ),
        migrations.AlterField(
            model_name='hoidong',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hoidong_giangvien',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hoidong_sinhvien',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kythuctap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='cau_hoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Home.cauhoi'),
        ),
        migrations.AlterField(
            model_name='luachon',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maukhaosat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nhiemvu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phanconggvhd',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phanconggvpt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phieutraloi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sinhvien_kythuctap',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tylediem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TieuChiDanhGia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.CharField(max_length=255)),
                ('cau_hoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieuchi', to='Home.cauhoi')),
            ],
        ),
    ]
