# Generated by Django 4.2.19 on 2026-03-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_remove_cauhoi_system_tag_remove_luachon_loai_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauhoi',
            name='system_tag',
            field=models.CharField(blank=True, choices=[('', 'Bình thường'), ('GVHD_1', 'Nguyện vọng GVHD 1'), ('GVHD_2', 'Nguyện vọng GVHD 2')], default='', max_length=50),
        ),
    ]
