# Generated by Django 4.2.19 on 2026-03-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_cauhoi_system_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauhoi',
            name='system_tag',
            field=models.CharField(blank=True, choices=[('', 'Bình thường'), ('GVHD_1', 'Nguyện vọng GVHD 1'), ('GVHD_2', 'Nguyện vọng GVHD 2'), ('HUONG_1', 'Hướng đề tài 1'), ('HUONG_2', 'Hướng đề tài 2'), ('GROUP', 'Làm nhóm'), ('GROUP_MEMBER', 'Thành viên nhóm')], default='', max_length=50),
        ),
    ]
