# Generated by Django 4.2.19 on 2026-03-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_cauhoi_system_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='noi_thuc_tap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cauhoi',
            name='system_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
