# Generated by Django 4.2.19 on 2026-03-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_sinhvien_noi_thuc_tap_alter_cauhoi_system_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sinhvien_kythuctap',
            name='ky_thuc_tap',
        ),
        migrations.RemoveField(
            model_name='sinhvien_kythuctap',
            name='sinh_vien',
        ),
        migrations.AlterUniqueTogether(
            name='bangdiem',
            unique_together={('sinh_vien', 'ky')},
        ),
        migrations.AlterUniqueTogether(
            name='hoidong_sinhvien',
            unique_together={('hoi_dong', 'sinh_vien')},
        ),
        migrations.AddIndex(
            model_name='bangdiem',
            index=models.Index(fields=['sinh_vien', 'ky'], name='Home_bangdi_sinh_vi_682faa_idx'),
        ),
        migrations.DeleteModel(
            name='SinhVien_KyThucTap',
        ),
    ]
