# Generated by Django 4.2.19 on 2026-03-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_sinhvien_kythuctap_ky_thuc_tap_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bangdiem',
            name='Home_bangdi_sinh_vi_682faa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='bangdiem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='hoidong_sinhvien',
            unique_together=set(),
        ),
    ]
