# Generated by Django 4.2.19 on 2026-03-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_bangdiem_home_bangdi_sinh_vi_682faa_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hoidong_sinhvien',
            unique_together={('sinh_vien', 'hoi_dong')},
        ),
    ]
